#!/bin/bash

# Build script to build Fluka with the GCR Source, assumes you are building in place

if [ -z $FLUPRO ] ; then
   echo "The FLUPRO environment isnt set, do you have Fluka installed?"
   exit
fi

if [ -z $FLUFOR ] ; then
   echo "The FLUFOR environment isnt set, do you have Fluka installed?"
   exit
fi


if [ -z $SRAGCODE_DIR ] ; then
    echo "Assuming building in place"
    export SRAGCODE_DIR=$PWD
else
    export SRAGCODE_DIR=$SRAGCODE_DIR
fi

# build source.f
$FLUPRO/flutil/fff RadSource/source.f
cp RadSource/source.o .
# build the executable
#$FLUPRO/flutil/lfluka -m fluka -L/$FLUPRO/ -a flukahp -L/$SRAGCODE_DIR/lib -a gcrsource -a stdc++ -a hdf5 -a dl -o flukahp RadSource/source.o
$FLUPRO/flutil/ldpmqmd -m fluka -L/$FLUPRO/ -a flukahp -L/$SRAGCODE_DIR/lib -a gcrsource -a stdc++ -L/data/opt/hdf5/lib -a hdf5 -a dl -o flukahp RadSource/source.o
