#!/bin/bash

# Build script to build Fluka with the GCR Source, assumes you are building in place

if [ -z $FLUPRO ] ; then
   echo "The FLUPRO environment isnt set, do you have Fluka installed?"
   exit
fi

if [ -z $FLUFOR ] ; then
   echo "The FLUFOR environment isnt set, do you have Fluka installed?"
   exit
fi


if [ -z $SRAGCODE_DIR ] ; then
    echo "Assuming building in place"
    export SRAGCODE_DIR=$PWD
else
    export SRAGCODE_DIR=$SRAGCODE_DIR
fi

# build source.f

#$FLUPRO/flutil/lfluka -o flukahp -L/$SRAGCODE_DIR/lib -l gcrsource -l stdc++ -L$HOME/data/opt/hdf5/hdf5.1.8.13/lib  -L/$FLUPRO/ -m fluka -a flukahp  source.o
cp RadSource/source.f .
$FLUPRO/flutil/ldpmqmd -m fluka -L/$SRAGCODE_DIR/lib -a gcrsource -a stdc++ -L$HOME/data/opt/hdf5/hdf5.1.8.13/lib -ahdf5 -adl -o flukahp source.f
# cleanup
rm source.f
rm source.o
